services:
  - type: web
    name: propertyfiling-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000