import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Server initialization logging
console.log('🚀 Starting Property List Backend Server...');
console.log(`📡 Server running on: http://localhost:${process.env.PORT || 3000}`);
console.log('🔍 API endpoints available at:');
console.log('   - GET  /api/properties');
console.log('   - POST /api/properties');
console.log('🌍 Environment:', process.env.NODE_ENV || 'development');

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
